/**
 * Game Constants and Type Definitions
 */

export const EffectType = {
  PERSIST: 'PERSIST',
  SCHEDULE_TRANSITION: 'SCHEDULE_TRANSITION',
  START_TIMER: 'START_TIMER',
  START_RECONNECT_TIMER: 'START_RECONNECT_TIMER',
  CANCEL_RECONNECT_TIMER: 'CANCEL_RECONNECT_TIMER',
  GAME_END: 'GAME_END',
};

export const EventType = {
  PLAYER_ACTION: 'PLAYER_ACTION',
  PLAYER_STATUS_UPDATE: 'PLAYER_STATUS_UPDATE',
  PLAYER_ELIMINATED: 'PLAYER_ELIMINATED',
  PLAYER_MOVED_TO_SPECTATOR: 'PLAYER_MOVED_TO_SPECTATOR',
  STATE_CHANGED: 'STATE_CHANGED',
  DEAL_STREET: 'DEAL_STREET',
  GAME_FINISHED: 'GAME_FINISHED',
  ERROR: 'ERROR',
};

export const TimerType = {
  ACTION_TIMEOUT: 'ACTION_TIMEOUT',
};



